### ISSUE TITLE
Automatically turned on shen nvim window get focused

### ISSUE THREAD

**Issue by aj3423** [dominikduda/vim_current_word#11]
Envrionment:  nvim 0.4   windows10-64bit

To reproduce this problem:

1. By default,  the plugin is on
2. Enter command  `:VimCurrentWordToggle`  to turn off plugin,  it works, no highlight anymore
3. Click any other application to make nvim lose focus
4. Switch back to nvim window
5. The plugin is on again

Configuration:

	call plug#begin('...')
	Plug 'dominikduda/vim_current_word'
	let g:vim_current_word#highlight_twins=1
	let g:vim_current_word#highlight_current_word=0
	nnoremap  <silent><c-l> :VimCurrentWordToggle<CR>
	call plug#end()

	color xxx

	" These has to be set after color scheme
	hi CurrentWordTwins gui=reverse 
	hi CurrentWord  gui=reverse

**Comment by aj3423** [comment]
This can be solved by 

    let g:vim_current_word#highlight_only_in_focused_window = 0

**Comment by dominikduda** [comment]
@aj3423 I created PR for this: https://github.com/dominikduda/vim_current_word/pull/13/files

Check if it solves your issue please by using (until its not on master):
`Plug 'dominikduda/vim_current_word', { 'branch': 'development' }`

Edit:
Reopen the issue if it is still not working, please.

**Comment by aj3423** [comment]
Thanks.  The `InsertEnter` and `InsertLeave` still causes problem. The previous focus problem is solved, but when enter insert mode, the plugin is enabled again. 
I commented out these two lines and everything works fine:

    " autocmd InsertEnter * call s:vim_current_word_disable()
    " autocmd InsertLeave * call s:vim_current_word_enable()

**Comment by dominikduda** [comment]
If you have these 2 lines in the plugin source, you are not using development. These lines are rewritten to:
```
  autocmd InsertEnter * call s:handle_insert_enter()
  autocmd InsertLeave * call s:handle_insert_leave()
```

Make sure you have latest changes from development, please.

**Comment by aj3423** [comment]
I tried delete the vim_current_word directory, and re-install it from VimPlug. I can confirm that the repository is set to 'development' from git. But there still have these two lines..

**Comment by dominikduda** [comment]
https://github.com/dominikduda/vim_current_word/blob/development/plugin/vim_current_word.vim

The issue has to be on your side. It works for me and it is just there as you can see above.

Edit:
You can just enter your plugin directrory and do `git checkout development`. This will also do the job.

**Comment by aj3423** [comment]
My bad.  It's fixed :)
