### ISSUE TITLE
Allow #delay_highlight to take milliseconds

### ISSUE THREAD

**Issue by HaleTom** [dominikduda/vim_current_word#17]
To have a customisable delay, would you consider letting `#delay_highlight` be a value in milliseconds?

**Comment by dominikduda** [comment]
I'll implement it.

Note for myself: `:help timer_start`, `:help timer_stop`

**Comment by dominikduda** [comment]
@HaleTom I implemented it, here is the PR: https://github.com/dominikduda/vim_current_word/pull/18

Would be awesome if you would switch to the PR branch and test it.
I will delay merging it to master for some time since the plugin has no tests :see_no_evil:
