### ISSUE TITLE
Highlight always disabled in insert mode

### ISSUE THREAD

**Issue by AndersBennedsgaard** [dominikduda/vim_current_word#21]
Hello from a Vim/Git newbie
I'd like to enable word highlighting in insert mode, but i've not been able to do this, even though i think this should be possible?

Some of my .vimrc config:
```
call plug#begin('~/.vim/plugged')
Plug 'dominikduda/vim_current_word', { 'branch': 'development' }
call plug#end()

let g:vim_current_word#highlight_twins=1
let g:vim_current_word#highlight_current_word=1
let g:vim_current_word#highlight_only_in_focused_window=0
let g:vim_current_word#disabled_by_insert_mode = 0
hi CurrentWord ctermbg=53
hi CurrentWordTwins ctermbg=239
```

I'm a windows user using MobaXterm with a SSH

**Comment by dominikduda** [comment]
`let g:vim_current_word#disabled_by_insert_mode = 0`
This variable is made up. It's not and has never been in the README.
It was never possible to enable the plugin in insert mode and I do not plan to add such feature.

**Comment by AndersBennedsgaard** [comment]
Fair enough that you don't plan on it, but 
`let g:vim_current_word#disabled_by_insert_mode = 0`
is absolutely a valid variable. 
Look at the second line in vim_current_word.vim:
```
let g:vim_current_word#disabled_by_focus_lost = 0
let g:vim_current_word#disabled_by_insert_mode = 0
let g:vim_current_word#timer_id = 0

" Clear previously scheduled highlight
function! vim_current_word#clear_scheduled_highlight()
...
```

I guess it is not doing what i wanted it to do, but okay then

**Comment by dominikduda** [comment]
This is a helper variable for inner workings.

Available features are described in README.

Looking into the code == hacking
There is no feature you are describing for end users.
