### ISSUE TITLE
Customized highlight does not work

### ISSUE THREAD

**Issue by zhou13** [dominikduda/vim_current_word#4]
I put the following in my vimrc but it does not work.
````
hi CurrentWord cterm=underline gui=underline
````

It seems that there is some problems with `s:hl_exists`.

**Comment by dominikduda** [comment]
It works for me in vim, gvim and nvim.
- What version of vim are you using?
- What system are you on?
- Is your plugin up to date?
- Is the code snippet you posted **below** plugins initialization in your `.vimrc`?

Answer these questions please and paste your `.vimrc`.

**Comment by khiet** [comment]
Thank you for the great plugin, @zhou13 it could be due to having the setting before setting `colorscheme` as it was the case for me.

**Comment by aj3423** [comment]
> ... due to having the setting before setting `colorscheme` ...

That's it,  it took me two hours investigating the problem, maybe this tip should be added to the document.

**Comment by dominikduda** [comment]
@aj3423 

Added this to FAQ in README. It will appear on main page readme whenever I'll merge development to master.

https://github.com/dominikduda/vim_current_word/commit/634e864f1f9a97b6c298fbbb7f8d2b5e8d456e78
