### ISSUE TITLE
:VimCurrentWordToggle behaves unexpectedly due InsertLeave autocmd re-enabling

### ISSUE THREAD

**Issue by jdsutherland** [dominikduda/vim_current_word#7]
Cheers for the nice plugin.

My usage preference is to have to plugin disabled by default, only selectively enabling using `:VimCurrentWordToggle`. The strange behavior is as follows:

1. Plugin toggled off
2. Enter/leave insert mode (InsertEnter and InsertLeave)
3. The plugin is now unexpectedly toggled on

Having a look, it seems to be from this autocmd:
https://github.com/dominikduda/vim_current_word/blob/58eac4039fc57c07a5a12a366736353391a747b8/plugin/vim_current_word.vim#L13

I'm not much familiar with Vim script so my lazy fix was to remove the InsertEnter/InsertLeave autocmd's. This seems preferable to unexpectedly toggling on from the off state.

**Comment by dominikduda** [comment]
Will look into it whenever I'll find some free time. Thanks for the report!

**Comment by dominikduda** [comment]
@jdsutherland  I created PR for this: https://github.com/dominikduda/vim_current_word/pull/14

Check if it solves your issue, please, by using (until its not on master):
`Plug 'dominikduda/vim_current_word', { 'branch': 'development' }`

Reopen the issue if it is still not working, please.
