### ISSUE TITLE
Add filetype blacklist option

### ISSUE THREAD

**Issue by liuchengxu** [dominikduda/vim_current_word#9]
Actually, I have run into this for a while, but I'm too lazy to find a solution :). Now someone else also pointed it out, see https://github.com/liuchengxu/space-vim-dark/issues/16. 

I guess this problem is related to vim_current_word. `:VimCurrentWordToggle` could solve the highlight issue in some filetypes, e.g., denite in above pic. I can also reproduce it in quickfix buffer. Then I resort to define an autocmd event to toggle this plugin automatically. But no luck. 

So, could you add an option for disabling this plugin in some filetypes? Thanks!

Here is my attempt:

```diff
diff --git a/plugin/vim_current_word.vim b/plugin/vim_current_word.vim
index e8e6364..efc87ef 100644
--- a/plugin/vim_current_word.vim
+++ b/plugin/vim_current_word.vim
@@ -5,6 +5,7 @@ let g:vim_current_word#twins_match_id = get(g:, 'vim_current_word#twins_match_id
 let g:vim_current_word#highlight_twins = get(g:, 'vim_current_word#highlight_twins', 1)
 let g:vim_current_word#highlight_current_word = get(g:, 'vim_current_word#highlight_current_word', 1)
 let g:vim_current_word#highlight_only_in_focused_window = get(g:, 'vim_current_word#highlight_only_in_focused_window', 1)
+let g:vim_current_word#blacklist = get(g:, 'vim_current_word#blacklist', [])

 augroup vim_current_word
   autocmd!
@@ -65,6 +66,7 @@ endfunction
 " Higlight current word and twins (aka 'main')
 function! s:highlight_word_under_cursor()
   if !g:vim_current_word#enabled | return 0 | endif
+  if index(g:vim_current_word#blacklist, &ft) >=0 | return 0 | endif
   call s:clear_current_word_matches()
   if s:character_under_cursor()=~#'\k'
     call s:add_current_word_matches()
```

**Comment by dominikduda** [comment]
Added it in this PR: https://github.com/dominikduda/vim_current_word/pull/15

Check if it solves your issue by using (until its not on master):
`Plug 'dominikduda/vim_current_word', { 'branch': 'development' }`

Reopen the issue if it does not work, please.

**Comment by HaleTom** [comment]
Thanks, I'm also using this feature.  How would I turn it off if there was no filetype detected?

**Comment by edrex** [comment]
@dominikduda #15 doesn't seem to work for me (neovim)

init-test.vim
```
call plug#begin('~/.vim/plugged')
  Plug 'dominikduda/vim_current_word'
call plug#end()
autocmd BufAdd NERD_tree_*,your_buffer_name.rb,*.js :let b:vim_current_word_disabled_in_this_buffer = 1
```
`vim -u init-test.vim hi.js`

Still underlines matches for word under cursor

(the BufAdd event doesn't seem to fire, so maybe it's something wrong with my vim.)
